### PR TITLE
Blog app - controllers specs

### PR DESCRIPTION
**Pull request by Alexr16**
### In this PR 🤖:
- Added RSpec gem  ✔️.
- Created a Request spec file for users and post controllers ✔️.
- Implemented tests for 🔖:
    - If the response status was correct ✔️.
    - If a correct template was rendered ✔️.
    - If the response body includes correct placeholder text ✔️.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @Alexr16, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ All linters passing
✔️ Professional Readme
✔️ Correct Gitflow

## Required 
- [ ] Kindly create a Request spec file for all your controllers as per the requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alexr16** [comment]
Hi @sja-thedude, thanks for your review.
The Request spec files for all my controllers are in the `/spec/controllers` folder.

**Review by julie-ify — APPROVED** [review]
Hi @Alexr16, 

- [ ] **[OPTIONAL]** Let me explain what the previous reviewer meant to communicate because it seems you do not understand the requested change. It is required that your `users_spec.rb` and `posts_spec.rb` are added to the `spec/requests/` directory instead of `spec/controllers/`. So, kindly rename your directory from `spec/controllers` to ` spec/requests/`.

Your tests all passed! Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alexr16** [comment]
Thanks, @julie-ify, for your explanation. I will take your recommendation.

**Pull request merged**
